---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: list space
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=ip_space_list

  - name: list subnet of a space
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=ip_subnet_list
     ipm_space='NY_space'
    register: eip
  
  - name: find one free IP address on a subnet
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=ip_address_find_free
     ipm_subnet_id=4
    register: eip

  - name: add IP on space
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=ip_address_add
     ipm_space='NY_space'
     ipm_hostname=put-your-hostname-here
     ipm_hostaddr='{{ eip.result.output }}'

  - name: delete IP address
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=ip_address_delete
     ipm_space='NY_space'
     ipm_hostaddr=192.168.1.152

  - name: add CNAME 
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=dns_cname_add
     ipm_alias_fqdn=alias.mydomain.net
     ipm_alias_value=hostname.mydomain.net
     ipm_alias_ttl=600

  - name: delete CNAME
    eip:
     ipm_server=<your_ipm_ipaddress_or_hostname_here>
     ipm_username=<your_ipm_user_here>
     ipm_password=<your_ipm_pwd_here>
     ipm_action=dns_cname_delete
     ipm_alias_fqdn=alias.mydomain.net

