---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
   ipm_server: <PUT-IPAM-HOSTNAME-OR-IP-HERE>
   ipm_username: <PUT-IPAM-USER-HERE>
   ipm_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63663431626463306331363739343039616365633137623066313738313537646664373364616131
          6566          PUT VAULTED PASSWORD HERE           346263386464633332333534393264
          31362323232323232323232323234224242424242424242424263763313133613239346361386165
          6566336631633264620a623239616632363737353164346466313939396466386233613836643933
          3766

  tasks:
   - name: find subnet of a space matching good class parameters
     no_log: true
     eip: ipm_server={{ ipm_server }} ipm_username={{ ipm_username }} ipm_password={{ ipm_password }} 
          ipm_action=ip_subnet_list
          ipm_space='NY_space'
          ipm_classparam='metadata1=somedata'
     register: goodsubnet

   - name: find one free IP address on this subnet
     no_log: true
     eip: ipm_server={{ ipm_server }} ipm_username={{ ipm_username }} ipm_password={{ ipm_password }} 
          ipm_action=ip_address_find_free
          ipm_subnet_id='{{ goodsubnet.result.output.0.ipm_subnet_id }}'
     register: freeip

   - name: add IP inside this subnet with needed class parameters
     no_log: true
     eip: ipm_server={{ ipm_server }} ipm_username={{ ipm_username }} ipm_password={{ ipm_password }} 
          ipm_action=ip_address_add
          ipm_space='NY_space'
          ipm_hostname=testhost.domain.net
          ipm_macaddr=00:11:22:33:44:55
          ipm_hostaddr='{{ freeip.result.output }}'
          ipm_classname='myclass'
          ipm_classparam='metadata2=somemoredata&metadata1=otherdata&hostname=testhost&domain=domain.net&persistent_dns_rr=1&dns_update=1&use_ipam_name=1&dhcpstatic=1'
